this is a dev commit: 4 files changed, 46 insertions(+), 58 deletions(-)
 LICENSE (gone) | 21 ---------------------

 action.yml     | 42 +++++++++++++++++++++++++++---------------

 main.sh (gone) | 21 ---------------------

 readme.md      | 20 +++++++++++++++++++-

message generated by QWD (github.com/nvfp/qwd)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,25 +1,37 @@
-name: "GitHub Action: Simple Release"
-description: "GitHub Action for creating simple GitHub Releases"
-author: "Nicholas Valentinus"
-branding:
-  icon: package
-  color: gray-dark
-
 inputs:
   tag:
-    description: "Release tag (also title)"
+    description: Release tag (also the title)
     required: true
   desc:
-    description: "Release description"
+    description: Release description
     required: true
 
 runs:
-  using: 'composite'
-  steps:      
-    - shell: bash
+  using: composite
+  steps:
+    - run: |
+        #!/bin/sh
+        echo "INFO: INPUT_TAG : '$INPUT_TAG'"
+        echo "INFO: INPUT_DESC: '$INPUT_DESC'"
+
+        # Check
+        if [ "$(echo "$INPUT_TAG" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$")" ]; then
+            status="latest"
+        elif [ "$(echo "$INPUT_TAG" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+b[0-9]*$")" ]; then
+            status="prerelease"
+        else
+            echo "ERROR: Invalid tag: $INPUT_TAG"
+            exit 1
+        fi
+        echo "INFO: status: '$status'"
+
+        # Release
+        if [ "$status" = "latest" ]; then
+            gh release create "$INPUT_TAG" --title "$INPUT_TAG" --notes "$INPUT_DESC"
+        elif [ "$status" = "prerelease" ]; then
+            gh release create "$INPUT_TAG" --title "$INPUT_TAG" --notes "$INPUT_DESC" --prerelease
+        fi
+      shell: bash
       env:
         INPUT_TAG: ${{ inputs.tag }}
         INPUT_DESC: ${{ inputs.desc }}
-      run: |
-        chmod +x $GITHUB_ACTION_PATH/main.sh
-        $GITHUB_ACTION_PATH/main.sh
